name: Tests
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint
        
      - name: Build
        run: yarn build